### PR TITLE
Add default size in SVG to prevent rendering problems in canvas

### PR DESCRIPTION
**Pull request by Trismegiste**
Hello,

I'm not sure if this PR is relevant but I've encountered a problem when I try to draw the generated SVG into a canvas (with some javascript like this) : 
```javascript
 window.addEventListener("load", function () {
            var myCanvas = document.querySelector('#myOutputCanvas')
            var ctx = myCanvas.getContext('2d')
            var img1 = new Image()
            img1.onload = function () {
                ctx.drawImage(img1, 0, 0)
            }
            var avatarId = 'Binx Bond';
// this doesn't work :
            var svgCode = multiavatar(avatarId);
// this works :
            svgCode = '<svg xmlns="http://www.w3.org/2000/svg" width="231" height="231" viewBox="0 0 231 231"><path .....'
            
            img1.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svgCode)
        })
```
When I copy-paste the content of the generated SVG and add the **height** and the **width** attributes into the svg root tag, it's ok.

I'm not an expert in SVG so if this PR would break other usages for your library, feel free to dismiss it.

Anyway, thank you for your time.

### CODE REVIEW

**Comment by giekaton** [comment]
Not providing widh and height is useful, because then the avatar SVG image inherits its size from the parent container and fills it 100%. It's very comfortable for regular web development.

As for canvas, I didn't test with it. Need to check, maybe there are some alternative ways to solve this. Maybe you can wrap the avatar with a fixed size container, or insert height and width into the SVG string before adding it to the canvas...

**Comment by Trismegiste** [comment]
I understand your choice to not provide height/width, it makes sense.

> maybe there are some alternative ways to solve this

Certainly. I'll investigate further. Thank you for your insight.

**Comment by Trismegiste** [comment]
Ok, let's forget everything, my problem is in fact a bug from Firefox :disappointed: 

https://bugzilla.mozilla.org/show_bug.cgi?id=700533

At least if someone has the same problem, she'll know

**Comment by giekaton** [comment]
Ok!

**Pull request closed without merging**
